### ISSUE TITLE
[Bug] Thornmarch EX not getting detected for novus light

### ISSUE THREAD

**Issue by Nyaruko731** [MidoriKami/ZodiacBuddy#26]
![image](https://user-images.githubusercontent.com/18459377/223947335-4e396cdb-aff0-4871-afa4-fdad9eea56cd.png)

Occured 9/3/23 between 7:19-7:55 (UTC+1)

**Comment by Nyaruko731** [comment]
![image](https://user-images.githubusercontent.com/18459377/224035839-9e8d0427-ea4a-4df6-a13c-ce5fe0ff7673.png)
And it worked later at 13:05 (UTC+1). Haven't touched anything in between.

**Comment by Hiroa** [comment]
From what I see in database, Thornmarch has already the bonus during the previous light window. (Maybe you can confirm that ?)
![image](https://user-images.githubusercontent.com/3938368/224080966-16bd9d3c-855e-4e7a-b350-7e2a45b363ba.png)

That would mean that duty can get the bonus two times (or more) in a row.
This is an issue since most of the detection is based on the fact that a same duty can't have bonus two time in row.

**Comment by Nyaruko731** [comment]
Sadly can't confirm that.
When quickly skimming thru official forum post for bonus light from 2014 there were definitely reports of same duty having bonus multiple windows in rows. 
https://forum.square-enix.com/ffxiv/threads/193628-Bonus-Light-windows-to-level-your-Novus-to-Nexus?p=2456666&viewfull=1#post2456666
8 hours of Thornmarch HM and such

**Comment by Hiroa** [comment]
I have some rows on db that show the same duty multiple time in row now (reset windows are on odd hours on utc+1)
![image](https://user-images.githubusercontent.com/3938368/225249728-31197726-bad0-492c-8585-42bd82678d7f.png)

**Comment by MidoriKami** [comment]
fixed in #36
